//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RalphStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHeader
    {
        public int OrderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> AccountNumber { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public int OrderDetails { get; set; }
        public int Address { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
